name: Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Evaluate Node.js version
        run: |
          export NODE_VERSION=$( cat .nvmrc )
          echo $NODE_VERSION
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: agaross.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
          tags: agaross.azurecr.io/agar-oss/agartex-app:latest
