name: Run tests

on: [pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: false
          target: test
          tags: agaross.azurecr.io/agar-oss/agartex-app:latest

      - name: Run tests
        run: docker run --rm agaross.azurecr.io/agar-oss/agartex-app
