name: Run tests

on: [pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build image
        run: docker build -t agaross.azurecr.io/agar-oss/agartex-app .

      - name: Run tests
        run: docker run --rm agaross.azurecr.io/agar-oss/agartex-app
